baseURL = "/"
languageCode = "en-us"
title = "YouTube Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "YouTube"
    subsite = "youtube"
    openGraphSiteName = "YouTube Tracking Exposed"
    description = "This is a collaborative project meant to let you take back control of your data. This approach do not follow corporate methods, but as an algorithm investigator let you passively records what Youtube algorithm pick for you, and let you play with the data."
    tagline = "Youtube is one of the way information spread; Only together, we can study its power."

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Youtuber Labor union"
    identifier = "SeeYou"
    name = "(concept) Youtuber Labor union"
    url = "/seeyou/"
    weight = -180
 [[menu.main]]
    page = "first results"
    identifier = "first-results"
    name = "First results"
    url = "/results/"
    weight = -170

 [[menu.main]]
    page = "More"
    identifier = "more"
    name = "More"
    url = "#"
    weight = -100
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "more"
    weight = -110
 [[menu.main]]
    page = "API Documentation"
    identifier = "api-documentation"
    parent = "more"
    name = "API Documentation"
    url = "/api-documentation/"
    weight = -130
 [[menu.main]]
    page = "Get Involved"
    identifier = "get-involved"
    name = "Get Involved"
    parent = "more"
    url = "/get-involved/"
    weight = -140
 [[menu.main]]
    page = "What We Collect, how does it work"
    identifier = "what-we-collect"
    name = "What We Collect"
    parent = "more"
    url = "/what-we-collect/"
    weight = -150
 [[menu.main]]
    page = "Impact"
    identifier = "impact"
    name = "Impact"
    parent = "more"
    url = "/impact/"
    weight = -160

 [[menu.featured]]
    page = "compare"
    identifier = "compare"
    name = "Compare"
    url = "/yttrex/compare/"
    weight = -180
    pre = "/images/yt-compare.jpg"
    post = "Compare how a video gets different reccomendations"
 [[menu.featured]]
    page = "related"
    identifier = "related"
    name= "Related"
    url = "/yttrex/related/"
    pre = "/images/yt-search.jpg"
    post = "Search if a video has ever been recommended by YouTube"
    weight = -170
 [[menu.featured]]
    page = "last"
    identifier = "last"
    name = "Last"
    url = "/yttrex/last/"
    pre = "/images/yt-last.jpg"
    post = "The lastest videos we have collected with our monitoring tools"
    weight = -160

 [[menu.footer]]
    page = "Project analysis"
    identifier = "initial-analysis"
    name = "Project analysis"
    url = "/initial-analysis/"
    weight = 100
 [[menu.footer]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    page = "ALEX"
    identifier = "alex"
    name = "Sponsoring project: Algorithms Exposed"
    url = "https://algorithms.exposed"
    weight = 80
